name = "jiandaoyun-proxy-worker"
main = "src/worker.js"
compatibility_date = "2026-03-15"
workers_dev = false

# 自定义域名路由 —— 注意 pattern 要带 /* 并且 custom_domain = true
[[routes]]
pattern = "jdy.lzc2002.top/*"
custom_domain = true

[observability]
[observability.logs]
enabled = true
invocation_logs = true